version: '3'
services:

  #apache-server
  webserver:
      image: bitnami/apache:latest
      restart: always
      ports:
        - "80:8080"
       
  #MySQL Service
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: yaslyk
      MYSQL_USER: bogdan
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"